name: .NET

on:
  release:
    types:
      - created
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '*.yml'
      - '*.yaml'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

        # This is important if you want auto-versioning.
      - name: Setup Dependencies
        run: |
          git config user.email "ninja@thesharp.ninja"
          git config user.name "Github Actions"
          nuget config -set signatureValidationMode=accept
          dotnet tool install -g nuke.globaltool --prerelease
          dotnet tool install -g gitversion.tool --prerelease
          dotnet tool install -g powershell

      - name: Build Debug and Test
        if: ${{ github.event_name == 'push' }}
        run: pwsh ./scripts/publish.ps1 "xxx" -WorkingFolder ./src -Verbose -WhatIf

      - name: Build Release and Publish
        if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        run: pwsh ./scripts/publish.ps1 "${{ secrets.NUGET_KEY }}" -WorkingFolder ./src -Verbose
                                                                                                      
