name: .NET

on:
  release:
    types:
      - created
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

      # This is important if you want auto-versioning.
    - name: Setup Gitversion
      run: |
        nuget.exe ./nuget.config trusted-signers add -name NuGet.org -serviceindex https://api.nuget.org/v3/index.json
        dotnet new tool-manifest # if you are setting up this repo
        dotnet tool install --local GitVersion.Tool --prerelease --configfile ./nuget.config
        if($LASTEXITCODE -ne 0) { throw 'Installing `GitVersion.Tool` 5.8.1 failed.' }
        dotnet tool install --local PowerShell --prerelease --configfile ./nuget.config
        if($LASTEXITCODE -ne 0) { throw 'Installing `Powershell` failed.' }
        dotnet dotnet-gitversion
        if($LASTEXITCODE -ne 0) { throw 'Executing `dotnet-gitversion` failed.' }

    - name: Build Debug and Test
      if: ${{ github.event_name == 'push' }}
      run: . ./SingleFileCSharp/build.ps1

#     - name: Build Release and Publish
#       if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
#       run: . ./scripts/publish.ps1 "${{ secrets.NUGET_KEY }}"
