name: .NET

on:
  release:
    types:
      - created
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

      # This is important if you want auto-versioning.
    - name: Setup Dependencies
      run: |
        nuget config -set signatureValidationMode=accept
        dotnet tool install -g nuke.globaltool --prerelease
        dotnet tool install -g gitversion.tool --prerelease

    - name: Build Debug and Test
      if: ${{ github.event_name == 'push' }}
      run: |
        cd ./SingleFileCSharp 
        . ./build.sh --root .

#     - name: Build Release and Publish
#       if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
#       run: . ./scripts/publish.ps1 "${{ secrets.NUGET_KEY }}"
