name: Template

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: windows-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

      # This is important if you want auto-versioning.
#     - name: Setup Powershell
#       run: dotnet tool install -g PowerShell

    - name: Merge Template
      run: |
        . scripts/template.ps1 -Verbose
        git add .
        git commit -m "Merged Template"
        git push ${{ github.repository }}
      
#     - name: Git Commit and Push
#       # You may pin to the exact commit or the version.
#       # uses: github-actions-x/commit@5cf7985b07155682f82d02b6c2188d90cebeb0c8
#       uses: github-actions-x/commit@v2.8
#       with:
#         # Github Token with commit access
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         # Override branch to push to
#         commit-message: Populated Template
