name: Template

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

      # This is important if you want auto-versioning.
    - name: Setup Powershell
      run: dotnet tool install -g PowerShell

    - name: Merge Template
      run: pwsh -f script/template.ps1 -Verbose
